from __future__ import annotations

import importlib
import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from PIL import Image

from ui_auto_gen.adapters.segmenter import SegmenterAdapter
from ui_auto_gen.raster import clamp_bbox, load_rgba_image, save_png
from ui_auto_gen.utils import write_json


@dataclass(frozen=True)
class Sam2Settings:
    checkpoint: Path
    model_cfg: str
    device: str
    model_size: str
    repo_root: Path


SAM2_MODEL_DEFAULTS = {
    "tiny": {
        "checkpoint": "models/sam2/sam2.1_hiera_tiny.pt",
        "model_cfg": "configs/sam2.1/sam2.1_hiera_t.yaml",
    },
    "small": {
        "checkpoint": "models/sam2/sam2.1_hiera_small.pt",
        "model_cfg": "configs/sam2.1/sam2.1_hiera_s.yaml",
    },
    "base_plus": {
        "checkpoint": "models/sam2/sam2.1_hiera_base_plus.pt",
        "model_cfg": "configs/sam2.1/sam2.1_hiera_b+.yaml",
    },
    "large": {
        "checkpoint": "models/sam2/sam2.1_hiera_large.pt",
        "model_cfg": "configs/sam2.1/sam2.1_hiera_l.yaml",
    },
}


class Sam2Segmenter(SegmenterAdapter):
    adapter_name = "sam2_segmenter"

    def __init__(self, settings: Sam2Settings) -> None:
        self.settings = settings
        self.model_metadata = {
            "model_family": "sam2",
            "model_size": settings.model_size,
            "checkpoint": str(settings.checkpoint),
            "model_cfg": settings.model_cfg,
            "device": settings.device,
        }

    @classmethod
    def from_env(cls, repo_root: Path, requested_size: str | None = None) -> "Sam2Segmenter":
        model_size = _normalize_model_size(os.environ.get("DESIGNUI_SAM2_MODEL_SIZE") or requested_size or "small")
        defaults = SAM2_MODEL_DEFAULTS[model_size]
        checkpoint = Path(os.environ.get("DESIGNUI_SAM2_CHECKPOINT", str(repo_root / defaults["checkpoint"])))
        model_cfg = os.environ.get("DESIGNUI_SAM2_MODEL_CFG", defaults["model_cfg"])
        device = os.environ.get("DESIGNUI_SAM2_DEVICE", "auto").lower()
        return cls(
            Sam2Settings(
                checkpoint=checkpoint,
                model_cfg=model_cfg,
                device=device,
                model_size=model_size,
                repo_root=repo_root,
            )
        )

    def segment(
        self,
        detections: list[dict[str, Any]],
        masks_dir: Path,
        image_size: tuple[int, int],
        base_image: Path | None = None,
    ) -> list[dict[str, Any]]:
        if base_image is None:
            raise RuntimeError("SAM2 segmentation requires a base image path.")
        if not self.settings.checkpoint.exists():
            raise FileNotFoundError(
                f"SAM2 checkpoint not found: {self.settings.checkpoint}. "
                f"Set DESIGNUI_SAM2_CHECKPOINT or download the SAM2 {self.settings.model_size} checkpoint under models/sam2/."
            )

        torch = importlib.import_module("torch")
        np = importlib.import_module("numpy")
        build_module = importlib.import_module("sam2.build_sam")
        predictor_module = importlib.import_module("sam2.sam2_image_predictor")
        build_sam2 = getattr(build_module, "build_sam2")
        predictor_cls = getattr(predictor_module, "SAM2ImagePredictor")

        device = self._resolve_device(torch)
        self.model_metadata["device"] = device
        model = build_sam2(self.settings.model_cfg, str(self.settings.checkpoint), device=device)
        predictor = predictor_cls(model)
        image = load_rgba_image(base_image, width=image_size[0], height=image_size[1]).convert("RGB")
        image_array = np.array(image)

        masks_dir.mkdir(parents=True, exist_ok=True)
        masks: list[dict[str, Any]] = []
        started = time.perf_counter()
        with torch.inference_mode():
            predictor.set_image(image_array)
            for detection in detections:
                mask = self._predict_mask(predictor, np, detection["bbox"], image.size)
                mask_id = f"mask_{detection['detection_id']}"
                mask_path = masks_dir / f"{mask_id}.json"
                mask_png_path = masks_dir / f"{mask_id}.png"
                save_png(Image.fromarray((mask["mask"] * 255).astype("uint8"), mode="L"), mask_png_path)
                payload = {
                    "schema_version": "1.0",
                    "mask_id": mask_id,
                    "shape": "sam2_mask",
                    "bbox": detection["bbox"],
                    "mask_png_path": str(mask_png_path),
                    "confidence": mask["score"],
                    "raw_model_output": {
                        "score": mask["score"],
                        "model": self.model_metadata,
                    },
                    "source": self.adapter_name,
                    "placeholder_visual": None,
                    "future_adapter": None,
                    "note": f"Generated by SAM2 {self.settings.model_size} from the detection bbox.",
                }
                write_json(mask_path, payload)
                masks.append(
                    {
                        "mask_id": mask_id,
                        "detection_id": detection["detection_id"],
                        "mask_path": str(mask_path),
                        "mask_png_path": str(mask_png_path),
                        "bbox": detection["bbox"],
                        "confidence": mask["score"],
                        "source": self.adapter_name,
                        "model": self.model_metadata,
                    }
                )

        self.model_metadata["elapsed_seconds"] = round(time.perf_counter() - started, 3)
        return masks

    def _resolve_device(self, torch: Any) -> str:
        requested = self.settings.device
        if requested == "auto":
            return "cuda" if torch.cuda.is_available() else "cpu"
        if requested == "cuda" and not torch.cuda.is_available():
            raise RuntimeError("DESIGNUI_SAM2_DEVICE=cuda was requested, but CUDA is not available.")
        if requested not in {"cpu", "cuda", "mps"}:
            raise RuntimeError(f"Unsupported SAM2 device: {requested}")
        return requested

    def _predict_mask(self, predictor: Any, np: Any, bbox: list[int], image_size: tuple[int, int]) -> dict[str, Any]:
        x1, y1, x2, y2 = clamp_bbox(bbox, image_size)
        box = np.array([x1, y1, x2, y2])
        masks, scores, _logits = predictor.predict(box=box, multimask_output=False)
        return {
            "mask": masks[0].astype("uint8"),
            "score": float(scores[0]),
        }


def _normalize_model_size(value: str) -> str:
    normalized = value.strip().lower().replace("-", "_").replace(".", "_")
    aliases = {
        "sam2": "small",
        "sam2_1": "small",
        "sam2_small": "small",
        "hiera_s": "small",
        "sam2_tiny": "tiny",
        "sam2_1_hiera_tiny": "tiny",
        "hiera_t": "tiny",
        "sam2_base_plus": "base_plus",
        "sam2_1_hiera_base_plus": "base_plus",
        "hiera_b+": "base_plus",
        "hiera_b_plus": "base_plus",
        "sam2_large": "large",
        "sam2_1_hiera_large": "large",
        "hiera_l": "large",
    }
    model_size = aliases.get(normalized, normalized)
    if model_size not in SAM2_MODEL_DEFAULTS:
        supported = ", ".join(sorted(SAM2_MODEL_DEFAULTS))
        raise RuntimeError(f"Unsupported SAM2 model size: {value}. Supported sizes: {supported}.")
    return model_size
